modLoader = "javafml"
loaderVersion = "[52,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/waterflane/PackControl/issues"

[[mods]]
modId = "packcontrol"
version = "${version}"
displayName = "PackControl"
displayURL = "https://github.com/waterflane/PackControl"
authors = "waterflane"
description = '''
A safe, transactional modpack updater for Minecraft 1.21.1.
'''
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "packcontrol-common.mixins.json"

[[dependencies.packcontrol]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.packcontrol]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

