package org.wodichka.packcontrol.updateformat;

public enum ManifestErrorCode {
    MANIFEST_REQUIRED,
    UNSUPPORTED_SCHEMA_VERSION,
    REQUIRED_VALUE,
    INVALID_VERSION,
    TOO_MANY_FILES,
    TOO_MANY_DOWNLOADS,
    TOO_MANY_OVERRIDE_ENTRIES,
    TOO_MANY_REMOVED_FILES,
    INVALID_SIZE,
    SIZE_LIMIT_EXCEEDED,
    TOTAL_SIZE_LIMIT_EXCEEDED,
    INVALID_DOWNLOAD_URL,
    INSECURE_DOWNLOAD_URL,
    DUPLICATE_DOWNLOAD,
    MISSING_HASH,
    INVALID_HASH,
    INVALID_ENVIRONMENT,
    INVALID_PATH,
    ABSOLUTE_PATH,
    DRIVE_PREFIXED_PATH,
    PATH_TRAVERSAL,
    INVALID_OVERRIDE_ARCHIVE,
    INVALID_OVERRIDE_ROOT,
    DUPLICATE_PATH,
    CONFLICTING_PATH
}
