modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/waterflane/PackControl/issues"

[[mods]]
modId = "packcontrol"
version = "${version}"
displayName = "PackControl"
displayURL = "https://github.com/waterflane/PackControl"
authors = "waterflane"
description = '''
A safe, transactional modpack updater for Minecraft 1.21.1.
'''

[[mixins]]
config = "packcontrol-common.mixins.json"

[[dependencies.packcontrol]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.packcontrol]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.packcontrol]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "CLIENT"
